"""add photo_url to courses

Revision ID: 5ee61e4aa675
Revises: 
Create Date: 2026-03-27 01:44:44.109788
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5ee61e4aa675'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'photo_url')
    # ### end Alembic commands ###
