"""add inferred flag to course_tees

Revision ID: 773aa2497a92
Revises: 5ee61e4aa675
Create Date: 2026-03-27 02:19:44.438668
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '773aa2497a92'
down_revision: Union[str, None] = '5ee61e4aa675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tees', sa.Column('inferred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_tees', 'inferred')
    # ### end Alembic commands ###
